### ISSUE TITLE
Scan value omits prefix

### ISSUE THREAD

**Issue by joe-campiondigital-mo** [goodeggs/barcode-scan-listener#5]
Hi, I have the following config:

```
barcodeScanListener.onScan({
  barcodePrefix: '',
  barcodeValueTest: /.*/,
  finishScanOnMatch: false,
  scanDuration: 500
}, function (barcode) {
  console.log(barcode)
})
```

When I scan a barcode any prefix/suffix is omitted in the result. Here are some examples:

Scanned directly into input/textarea `00901765` 
console logs `0901765`

Scanned directly into input/textarea `5705831019096` 
console logs `705831019096`

Maybe there is some barcode knowledge i'm missing or a setting I can change in the config - any help would be much appreciated.

**Comment by joe-campiondigital-mo** [comment]
Ok, just checked the code and realised it requires a prefix value

**Comment by darkurse** [comment]
why is this required though ?

I have done this udpate in the code to have the ability to make it optional .. Should I make a PR ?

```js
      if (prefixBuffer === expectedPrefixSlice && char === barcodePrefix.charAt(charIndex)) {
        prefixBuffer += char;
      } else if (matchedPrefix     || barcodePrefix === ''   ) {
        valueBuffer += char;
      }
```

**Comment by serhalp** [comment]
@darkurse if you have a fix for this bug (when using an empty `barcodePrefix`, the handler is called with the first character truncated), we'd gladly accept a PR! If you can add a test for this case, that'd be great too. Thank you!
